-- ============================================================
-- MIGRATION 034: In-App Messaging
-- ============================================================
-- Date: March 2026
--
-- Adds two tables for thread-scoped in-app messaging between
-- employers and candidates (drivers / developers).
--
-- Design decisions:
--   - Every thread is anchored to an existing relationship context
--     (application or candidate_request) to prevent cold-message spam.
--   - messages.read_at IS NULL means the recipient has not yet read it.
--   - message_threads.last_message_at + last_message_preview power the
--     inbox sort order and preview without extra joins.
-- ============================================================

-- ── Thread container ─────────────────────────────────────────────────────────

CREATE TABLE message_threads (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The two participants. We store them as a canonical pair so
  -- (a < b by UUID text sort) to simplify unique enforcement.
  participant_a_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  participant_b_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Optional context anchors (at least one must be non-null; enforced by CHECK)
  application_id         UUID REFERENCES applications(id) ON DELETE SET NULL,
  candidate_request_id   UUID REFERENCES candidate_requests(id) ON DELETE SET NULL,

  -- Human-readable subject auto-generated by the API
  subject                TEXT NOT NULL DEFAULT '',

  -- Denormalised for O(1) inbox queries
  last_message_at        TIMESTAMPTZ,
  last_message_preview   TEXT,

  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One thread per pair-per-context to prevent duplicates
  UNIQUE (participant_a_user_id, participant_b_user_id, application_id),
  UNIQUE (participant_a_user_id, participant_b_user_id, candidate_request_id),

  CONSTRAINT participants_differ CHECK (participant_a_user_id <> participant_b_user_id),
  CONSTRAINT has_context CHECK (application_id IS NOT NULL OR candidate_request_id IS NOT NULL)
);

CREATE INDEX idx_message_threads_participant_a ON message_threads (participant_a_user_id, last_message_at DESC);
CREATE INDEX idx_message_threads_participant_b ON message_threads (participant_b_user_id, last_message_at DESC);

COMMENT ON TABLE message_threads IS
  'Conversation threads between an employer and a candidate, anchored to an application or candidate_request.';

-- ── Individual messages ───────────────────────────────────────────────────────

CREATE TABLE messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id       UUID NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
  sender_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body            TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  read_at         TIMESTAMPTZ,   -- NULL = unread by the other participant
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_thread_created ON messages (thread_id, created_at ASC);

COMMENT ON TABLE messages IS
  'Individual messages within a message_thread. read_at IS NULL means unread by the recipient.';
